### PR TITLE
Fix automatic backups

### LINKED ISSUE #900: Automatic backup does not seem to be working properly
Version: 0.6.1
Android version: 7.1.2
Device: Google Pixel XL, (also tested on Samsung Galaxy S8+, Google Nexus 7 (2013), Amazon Fire 8 (7th gen))

I have enabled automatic library backups, but no files are being written to the specified backup directory. Not sure how else to troubleshoot the problem. Please let me know if there is any additional information I can provide to help!

### PR DESCRIPTION
**Pull request by NoodleMage**
This closes #900 

~Probably needs some more testing and stuff. But tested working on Android 8.0.0.~

~Fix is using a correct URI call + creating the directory through:~
~`val autoDir = dir.createDirectory(getString(R.string.automatic_backup))`~

~If you have a cleaner solution let me know ;)~

Tested working on: API 19,26 and 27

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt [hunk 1]
```diff
@@ -161,7 +160,7 @@ class SettingsBackupController : SettingsController() {
             CODE_BACKUP_DIR -> if (data != null && resultCode == Activity.RESULT_OK) {
                 val activity = activity ?: return
                 if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
-                    val uri = Uri.fromFile(File(data.data.path))
+                    val uri = data.data
```
Comment (inorichi) [inline app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt]: This if/else could be simplified with the new change

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -231,6 +231,7 @@
     <string name="backup_choice">What do you want to backup?</string>
     <string name="restoring_backup">Restoring backup</string>
     <string name="creating_backup">Creating backup</string>
+    <string name="automatic_backup">automatic</string>
```
Comment (inorichi) [inline app/src/main/res/values/strings.xml]: I think this should be a hardcoded string. We don't want translations on this one.

File: app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupCreateService.kt [hunk 3]
```diff
@@ -113,20 +114,21 @@ class BackupCreateService : IntentService(NAME) {
         try {
             // When BackupCreatorJob
             if (isJob) {
-                // Get dir of file
+                // Get dir of file and create
                 val dir = UniFile.fromUri(this, uri)
+                val autoDir = dir.createDirectory(getString(R.string.automatic_backup))
```
Comment (inorichi) [inline app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupCreateService.kt]: You could keep the previous variable and append `.createDirectory(...)` since `dir` is not being used anywhere else.
